theme: jekyll-theme-minimal
title: Obsolete Removable Media Guide
description: Resource for accessing files from obsolete removable media 
logo: https://github.com/frannietrempe/Obsolete-Removable-Media-Guide/blob/master/images/resized/5.25inch_floppy_logo.jpg?raw=true
