theme: jekyll-theme-minimal
title: Obsolete Removable Media Guide
description: This resource was created by Becca Bender and Frannie Trempe in 2018 as a part of the Handling Complex Media class in New York University's Moving Image Archiving and Preservation Program.

Special thanks to Ethan Gates, Nicole Martin, and Amy Brost for their invaluable assistance.

This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/). 
logo: https://github.com/frannietrempe/Obsolete-Removable-Media-Guide/blob/master/images/resized/5.25inch_floppy_logo.jpg?raw=true
