theme: jekyll-theme-minimal
title: Obsolete Removable Media Guide
description: Resource for mounting obsolete removable media and accessing contained files 
logo: https://github.com/frannietrempe/Obsolete-Removable-Media-Guide/blob/master/images/resized/5.25inch_floppy_logo.jpg?raw=true
baseurl: /Obsolete-Removable-Media-Guide
